Repository COOL-cohort/COOL, pull requests merged in 2022-08, with the labels that each got.

#81 Fix some typo
  cool-core/src/main/java/com/nus/cool/core/cohort/refactor/CohortProcessor.java
  cool-core/src/main/java/com/nus/cool/core/cohort/refactor/aggregate/AggregateFunc.java
  cool-core/src/main/java/com/nus/cool/core/cohort/refactor/aggregate/AverageAggregate.java
  cool-core/src/main/java/com/nus/cool/core/cohort/refactor/aggregate/CountAggregate.java
  cool-core/src/main/java/com/nus/cool/core/cohort/refactor/aggregate/DistinctCountAggregate.java
  cool-core/src/main/java/com/nus/cool/core/cohort/refactor/aggregate/MaxAggregate.java
  cool-core/src/main/java/com/nus/cool/core/cohort/refactor/aggregate/MinAggregate.java
  cool-core/src/main/java/com/nus/cool/core/cohort/refactor/aggregate/SumAggregate.java
  cool-core/src/main/java/com/nus/cool/core/cohort/refactor/birthSelect/BirthContextWindow.java
  cool-core/src/main/java/com/nus/cool/core/cohort/refactor/birthSelect/BirthSelectionContext.java
  cool-core/src/main/java/com/nus/cool/core/cohort/refactor/birthSelect/EventSelection.java
  cool-core/src/main/java/com/nus/cool/core/cohort/refactor/filter/RangeFilter.java
  cool-core/src/main/java/com/nus/cool/core/cohort/refactor/filter/SetFilter.java
  cool-core/src/main/java/com/nus/cool/core/cohort/refactor/valueSelect/ValueSelection.java
Labels: documentation

#88 Add more functionality test (average, sum, max, min)
  cool-core/src/main/java/com/nus/cool/core/cohort/refactor/aggregate/AverageAggregate.java
  cool-core/src/main/java/com/nus/cool/core/cohort/refactor/aggregate/MaxAggregate.java
  cool-core/src/main/java/com/nus/cool/core/cohort/refactor/aggregate/MinAggregate.java
  cool-core/src/main/java/com/nus/cool/core/cohort/refactor/aggregate/SumAggregate.java
  cool-core/src/test/java/com/nus/cool/core/refactor/ProcessorTest.java
  datasets/health_raw/run.sh
  datasets/health_raw/sample_query_average/generateTrue.py
  datasets/health_raw/sample_query_average/query.json
  datasets/health_raw/sample_query_average/query_result.json
  datasets/health_raw/sample_query_distinctcount/generateTrue.py
  datasets/health_raw/sample_query_distinctcount/query.json
  datasets/health_raw/sample_query_distinctcount/query_result.json
  datasets/health_raw/sample_query_max/generateTrue.py
  datasets/health_raw/sample_query_max/query.json
  datasets/health_raw/sample_query_max/query_result.json
  datasets/health_raw/sample_query_min/generateTrue.py
  datasets/health_raw/sample_query_min/query.json
  datasets/health_raw/sample_query_min/query_result.json
  datasets/health_raw/sample_query_sum/generateTrue.py
  datasets/health_raw/sample_query_sum/query.json
  datasets/health_raw/sample_query_sum/query_result.json
Labels: enhancement

#99 create github action
  .github/workflows/maven.yml
Labels: enhancement, code-clean
